### PR TITLE
Add logo to readme

### PR DESCRIPTION
**Pull request by Technical-Coder**

### CODE REVIEW

**Review by eyx092 — CHANGES_REQUESTED** [review]
Could you perhaps make the logo larger?

**Comment by Technical-Coder** [comment]
Can you try this one? https://github.com/Technical-Coder/mathscript/blob/main/mathscript_logo.png

**Comment by eyx092** [comment]
Sure

**Review by eyx092 — APPROVED** [review]
Alright, I don't know... it pretty much looks the same... I'll approve it, whatever

**Pull request merged**
